<?php

namespace AppBundle\Repository;

/**
 * EpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function nextDiffusions(){
        return $this->createQueryBuilder('episode')
            ->where('episode.date > :today')
            ->setParameter('today', date("Y-m-d", time()))
            ->orderBy('episode.date')
            ->getQuery()->getResult();
    }
}
