<?php

namespace AppBundle\Repository;
use AppBundle\Entity\TVShow;

/**
 * TVShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TVShowRepository extends \Doctrine\ORM\EntityRepository
{

	public function findAllAsQueryBuilder() {
		return $this->createQueryBuilder("show");
	}

    /**
     * @param $search
     * @return \Doctrine\ORM\QueryBuilder
     */
	public function listAsQueryBuilderWhereNameIsLike($search) {
		return $this->createQueryBuilder('show')
			->where("show.name LIKE :name")
			->setParameter('name', "%".$search."%");
	}

	public function addOmdbShow($name, $image, $plot){

        $show = new TVShow();
        $show->setSynopsis($plot);
        $show->setImage($image);
        $show->setName($name);
        $this->getEntityManager()->persist($show);
        $this->getEntityManager()->flush();
    }
}
