<?php

namespace AppBundle\Repository;
use AppBundle\Entity\TVShow;

/**
 * TVShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TVShowRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $search
     * @return \Doctrine\ORM\QueryBuilder
     */
	public function searchShowsLike($search) {
		return $this->createQueryBuilder('show')
			->where("show.name LIKE :name")
			->setParameter('name', "%" . $search . "%");
	}
}
